### ISSUE TITLE
Problems with `content-encoding`

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#10]
It seems there is still a bug regarding the headers. I did tests on ld.geo.admin.ch

`curl 'https://ld.geo.admin.ch/boundaries/canton/2:2017' -H 'Pragma: no-cache' -H 'Accept-Language: en-US,en;q=0.8,de;q=0.6,fr;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: application/ld+json' -H 'Cache-Control: no-cache' -H 'Cookie: _ga=GA1.2.1259596876.1477662581' -H 'Connection: keep-alive' --compressed`

If the `--compressed` flag is set the query does not work. It seems that the answer is not compressed, but the content-encoding Response header still says gzip.

If we overwrite the response-header manually it works.

**Comment by l00mi** [comment]
Okay, now I am sure, the content-encoding header does state gzip, but non compressed result is delivered.

**Comment by bergos** [comment]
Fixed in latest version with [this commit](https://github.com/zazukoians/trifid-handler-sparql/commit/e9492a196c76ee709c5607d57294a5ba49d65cb6).
