### ISSUE TITLE
Show the origin of triple by Named Graph and/or Endpoint

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#102]
To make it clear where the triples come from to the end-user we should be able to also show the Named Graph and/or Endpoint in the HTML interface to the enduser.

I can imagine either one column more for NG and to state the Endpoint in the top corner. Or even to smartly re-group the triples which are from one NG.

**Comment by cristianvasquez** [comment]
Reviewed. Development is being tracked at:  https://github.com/zazuko/trifid/issues/121

**Comment by l00mi** [comment]
Where is the Metadata panel handled? I think it should be a own Web-component ideally.

* The endpoint used should be accessible to be used anywhere in the design. (It will for ld.admin.ch go to the footer most probably.)
* The idea of the list of namedgraph with counts is nice. It seems that only the "default graph" is shown in the bottom overview. https://lindas.zazukoians.org/canton/23 -> This should also be accessible by the page renderer.
* Ideally it is possible to show for each triple the "named graph". (Or is this already possible @cristianvasquez ?)

**Comment by cristianvasquez** [comment]
The metadata panel is in the trifid-renderer-entity

**Comment by cristianvasquez** [comment]
Misclicked the 'close' button :) 

The metadata panel is in the trifid-renderer-entity middleware.

https://github.com/zazuko/trifid-renderer-entity/blob/main/renderer/web-component/Metadata.js

I agree on having a specialized Web-Component.

**Comment by cristianvasquez** [comment]
I've just realized that the named-graph is not correctly fetched in the https://ld.zazuko.com I have to investigate why
