### ISSUE TITLE
Optimize the Listed Predicate 

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#103]
##  Show the prefix if known instead only the term 
* In examples like: https://register.ld.admin.ch/zefix/company/1198554/address it is not clear anymore from which ontology a predicate comes from by only showing the Term which is confusing.
* If available it should also show the (multilingual) label of the predicate, instead of the prefix:term. (But should also provide easy access to the "term".

## Regroup/Order the Predicates to make sense.
* Currently there is no order / grouping of the predicates, which can be confusing. We should have a heuristic to group and then sort the predicates.

* If the Object is identical regroup the predicates in the same line

**Comment by cristianvasquez** [comment]
Reviewed. Development is being tracked at:  https://github.com/zazuko/trifid/issues/121

**Comment by l00mi** [comment]
@cristianvasquez do we have an example for this? @ludovicm67 also here an instance pointing to lindas prod would be usefull.

**Comment by ludovicm67** [comment]
Regarding the instance pointing to Lindas, I will take care of it today.

**Comment by cristianvasquez** [comment]
Hi @l00mi, I'm looking at the issue again, and it describes about two different features.

> ## Regroup/Order the Predicates to make sense.

Currently, the renderer has some options that configure this behavior.


  groupValuesByProperty: true,
  groupPropertiesByValue: true,

https://github.com/zazuko/rdf-entity-webcomponent/blob/21d911e5c6093d492c0a7e0945d1be1044730858/src/builder/entityBuilder.js#L99

> ## Show the prefix if known instead only the term

The renderer uses a specific set of vocabularies to render  into account.
```js
schema, rdf, rdfs, skos, foaf, dash, xsd, sh, skosxl, vcard
````
Additional ones can be added one by one.

```js
        ns.ex = rdf.namespace('http://example.org/')
````


![image](https://user-images.githubusercontent.com/361916/204762583-0d7f8ac8-9f91-4c01-a533-596e4890399e.png)

**Comment by cristianvasquez** [comment]
When the examples are deployed I can post a link to examples
