### ISSUE TITLE
Provide the label for Objects of the Resources in the default query

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#104]
In cases like https://ld.admin.ch/country/CHE all Cantons are listed.. but the `term` only shows a number.

Where available first show the (multilingual) label, based on following prio:
* skos:prefLabel
* rdfs:label
* schema:name

The new front-end reader will correctly incorporate these labels, but the Standard Triffid Query should be changed to also provide labels for object is available.

**Comment by cristianvasquez** [comment]
Reviewed. Development is being tracked at:  https://github.com/zazuko/trifid/issues/121

**Comment by l00mi** [comment]
@cristianvasquez some questions:
1) Is there an instance online which can be used to tewst this?
2) Can the list of predicates be configured? if yes how?
3) Is the default DESCRIBE query of Trifid adopted to always provide the labels in the view where available?

**Comment by cristianvasquez** [comment]
>    Is there an instance online which can be used to tewst this?
I will post links when it's online


>    Can the list of predicates be configured? if yes how?

```
    labelProperties: [
      ns.foaf.name, ns.skos.prefLabel, ns.schema.name, ns.rdfs.label],
````
Using a parameter configured in trifid or as web component

https://github.com/zazuko/rdf-entity-webcomponent/blob/21d911e5c6093d492c0a7e0945d1be1044730858/src/builder/entityBuilder.js#L100

>    Is the default DESCRIBE query of Trifid adopted to always provide the labels in the view where available?

When you say default, you mean trifid-handler-sparql?

Today the default sparql describe is this one: https://github.com/zazuko/trifid-handler-sparql/blob/a3bb38be2c2b3c1f380afef94e2e0f778e25c833/index.js#L10

But I'm afraid I don't understand the question, Isn't DESCRIBE implemented in the triplestore?

**Comment by cristianvasquez** [comment]
@l00mi Please add a short message when changing the issue title explaining 'why', otherwise, this leads to confusion.

**Comment by cristianvasquez** [comment]
I've tested it with the following query:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
    ?subject ?predicate ?object
}
WHERE {
   {
     ?subject ?predicate ?object .
      VALUES ?subject { <${iri}> }
   }
   UNION
   {
       <${iri}> ?pp ?subject .
       ?subject ?predicate ?object .
       VALUES ?predicate {
           foaf:name
           skos:prefLabel
           schema:name
           rdfs:label
       }
   }
}
```

But I haven't changed the default query. I don't know the consequences of changing the DESCRIBE that's there (follows blank nodes)

**Comment by l00mi** [comment]
Please deploy also on https://lindas.zazukoians.org/canton/23

**Comment by cristianvasquez** [comment]
Deployed!
