### ISSUE TITLE
Discuss refactoring of config system

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#108]
- One package/plugin can be used multiple times in different pathes or vhosts
- It should be possible to configure setups like the following with the same level complexity
  - [Base Setup with adapted design](https://gitlab.zazuko.com/docker/lod-basel/-/blob/master/config.json)
  - [Multi-Source Setup](https://github.com/zazuko/rdf-cube-schema/blob/main/trifid/config.json)
- Features can be composed by combining different configs (baseConfig single value will be replaced by an array of configs to merge)
  - SPARQL base
  - SPARQL full (yasgui, graph-explorer, spex)
- Add a function to generate a router object out of a given configuration
  - It should be possible to use a config in custom code

**Comment by bergos** [comment]
The outcome of todays (2022-04-19) discussion:

# config

## Middlewares

All middlewares are defined in the `middlewares` property.
The value of the property is an object.
Each middleware instance uses it own key.
The order of loading the middlewares is defined by the value of the `order` property.
The `module` property points to the module to load.
A string is used that will be processed by ESM `import()`.

```json
{
  "middlewares": {
    "templateEngine": {
      "order": 10,
      "module": "trifid-plugin-cotton-candy"
    }
  }
}
```

### Config

Properties defined in `globals` are merged into the scoped config.
The value given in `globals` can be overwritten in the scoped config.
Using a `null`-value will prevent merging the specific property.

```json
{
  "globals": {
    "endpointUrl": "env:SPARQL_ENDPOINT_URL"
  },
  "middlewares": {
    "templateEngine": {
      "order": 10,
      "module": "trifid-plugin-cotton-candy",
      "config": {
        "endpointUrl": "env:ENDPOINT_URL",
        "empty": null
      }
    }
  }
}
```

### Middleware Factory

The middleware factory is called with the scoped config as the first argument.
As a second argument the full processed config is given (resolved variables).

```javascript
function factory (scopedConfig, completeConfig) {
  return (req, res, next) => {
    
  }
}
```

**Comment by cristianvasquez** [comment]
Regarding middlewares, from the WIKI:

```
All middlewares are defined in the middlewares property. The value of the property is an object. Each middleware instance uses it own key. The order of loading the middlewares is defined by the value of the order property. The module property points to the module to load. A string is used that will be processed by ESM import().

{
  "middlewares": {
    "templateEngine": {
      "order": 10,
      "module": "trifid-plugin-cotton-candy"
    }
  }
}
```

Since now the string is processed by ESM import(), should be the .js extension mandatory? It would be consistent with ESM import(). Trifid could error explaining the mismatch.  Does it make sense?
