### ISSUE TITLE
Implement interfaces for handlers in plain middleware

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#109]
At the moment handlers are loaded by the core/handler plugin.
Handlers are just middlwares that rely on the `req.absoluteUrl()` method.
The structure could be simplified in the same way it's done for all other plugins #98

**Comment by ludovicm67** [comment]
It will not be plain middlewares.
They should implement a middleware factory, like described here: https://github.com/zazuko/trifid/wiki/Configuration#middleware-factory
