### ISSUE TITLE
Use ESM in all Trifid packages

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#110]
All packages should be converted from CommonJS to ESM.

**Comment by cristianvasquez** [comment]
All the trifid repositories (that are not instances) that I found:

## Trifid

visibility: public

https://github.com/zazuko/trifid

description: Lightweight Linked Data Server and Proxy

## Trifid-core

- [ ] Move to ESM
visibility: public

https://github.com/zazuko/trifid-core

description: Trifid Core

## Plugins

### Trifid-plugin-cotton-candy
- [ ] Move to ESM
visibility: public

https://github.com/zazuko/trifid-plugin-cotton-candy

Trifid Cotton Candy template engine plugin 

### Trifid-plugin-hydra-box
- [ ] Move to ESM
visibility: public

https://github.com/zazuko/trifid-plugin-hydra-box

Trifid Hydra Box plugin 

### Trifid-plugin-markdown
- [ ] Move to ESM
visibility: public

https://github.com/zazuko/trifid-plugin-markdown

Trifid Markdown plugin

### Trifid-plugin-renderer
- [ ] Move to ESM
visibility: public

https://github.com/zazuko/trifid-plugin-renderer

Trifid graph HTML render plugin 

### Trifid-renderer-simple
- [ ] Move to ESM
visibility: private

https://github.com/zazuko/trifid-renderer-simple

A simple renderer for Trifid 

### Trifid-plugin-yasgui
- [ ] Move to ESM
visibility:public

https://github.com/zazuko/trifid-plugin-yasgui

YASGUI for Trifid 

### Trifid-plugin-graph-explorer

visibility: public

https://github.com/zazuko/trifid-plugin-graph-explorer

### Trifid-plugin-spex

visibility: public

https://github.com/zazuko/trifid-plugin-spex

SPEX for Trifid 

### Trifid-plugin-i18n

visibility: public

https://github.com/zazuko/trifid-plugin-i18n

Trifid plugin for i18n support 

## Handlers

### Trifid-handler-sparql
- [ ] Move to ESM
visiblity: public

https://github.com/zazuko/trifid-handler-sparql

### Trifid-handler-fetch
- [ ] Move to ESM
visibility: public

https://github.com/zazuko/trifid-handler-fetch

Fetch handler for Trifid 

### Trifid-handler-fs

visibility: public

https://github.com/zazuko/trifid-handler-fs

File system handler for Trifid 

### Trifid-handler-file

visibility: public

https://github.com/zazuko/trifid-handler-file

File handler for Trifid

**Comment by cristianvasquez** [comment]
@ludovicm67 @bergos 
Is [this](https://github.com/zazuko/trifid/wiki/Packages) the list of packages to move to ESM?

**Comment by ludovicm67** [comment]
This would be a nice start: https://github.com/search?q=org%3Azazuko+trifid-plugin+user%3Azazuko&type=Repositories

**Comment by cristianvasquez** [comment]
Some pull requests

https://github.com/zazuko/trifid-plugin-yasgui/pull/3
https://github.com/zazuko/trifid-plugin-iiif/pull/1
https://github.com/zazuko/trifid-plugin-graph-explorer/pull/8

**Comment by l00mi** [comment]
Lets try to deploy a first version on https://ld.zazuko.com/

**Comment by cristianvasquez** [comment]
Could you please provide more details?

There is some source code, config files or data to start from?

**Comment by l00mi** [comment]
You would need to ask @ludovicm67 plese.

**Comment by ludovicm67** [comment]
The repo for ld.zazuko.com is here: https://github.com/zazuko/ld.zazuko.com
It will automatically deploy on new SemVer tags.

You can do some tests in the https://github.com/zazuko/trifid-pocs repo if you want.

You can ask more details to @bergos if needed.

**Comment by cristianvasquez** [comment]
The status of this can be checked against the https://github.com/orgs/zazuko/projects/14/views/2 instance.

**Comment by Irosch** [comment]
Create a meeting to discuss:
- @ludovicm67 please help deploy new default instance 2.3 (ld.zazuko.com)
- test the instance 
- create new issues for discovered problems
