### ISSUE TITLE
Define core packages for restructuring/refactoring

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#113]
Of all the packages defined in the [wiki](https://github.com/zazuko/trifid/wiki/Packages) we should define a list of packages that are used to test new concepts like #112 #111 #109 .

**Comment by ludovicm67** [comment]
I updated the wiki page to order them by categories, so that it is more clear.
Most of the plugins are already up-to-date, and some of them should be deprecated in favor of others or because they will be directly shipped with the core.
