### ISSUE TITLE
Trifid-handler-fetch - Move to ESM and Test

### ISSUE THREAD

**Issue by cristianvasquez** [zazuko/trifid#117]

**Comment by cristianvasquez** [comment]
This waits for: https://github.com/rdf-ext/rdf-utils-dataset to be published

**Comment by l00mi** [comment]
@bergos is the above published meanwhile? If so can you verify that the trifid-handler-fetch does indeed work as ESM module?

**Comment by bergos** [comment]
@l00mi you can have a look here: https://tbbt.zazukoians.org/data/person/penny

**Comment by l00mi** [comment]
So we can close this?
