### ISSUE TITLE
Update default trifid instance and deploy on ld.zazuko.com

### ISSUE THREAD

**Issue by Irosch** [zazuko/trifid#122]
Final goal to have the default instance should be online on ld.zazuko.com

**Comment by Irosch** [comment]
Co-programming with Thomas

**Comment by bergos** [comment]
The initial work to have a tbbt instance was done here: https://github.com/zazuko/trifid-pocs/tree/main/tbbt

**Comment by cristianvasquez** [comment]
Two running instances at:

https://github.com/zazuko/trifid-pocs/tree/main/ld.zazuko.com with default renderer
https://github.com/zazuko/trifid-pocs/tree/main/tbbt, with clownface renderer

**Comment by l00mi** [comment]
@cristianvasquez is meeting with @ludovicm67 to deploy the new default instance.

**Comment by l00mi** [comment]
Looks good. @ludovicm67 how to upgrade with latest version if needed?

**Comment by ludovicm67** [comment]
Someone needs to increase versions of dependencies (if there are some updates) in the `package.json` file on the https://github.com/zazuko/ld.zazuko.com repo and regenerate the lock file using `yarn`, push the changes, run `npm version major/minor/patch` and then `git push && git push --tags`, then it will be automatically deployed and the instance updated.
