### ISSUE TITLE
Document and update the objectives of Trifid for externals

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#125]
The readme of Trifid should be updated. Below is an initial draft how it could look like:

First DRAFT:

# Trifid

## What is Trifid?

It's a Web server specialized in Linked Data. 

The main functionalities of trifid are:

### Provide a SPARQL endpoint (proxy)
Backed by another SPARQL endpoint.
*or* 
backed by a file.

### Dereference Linked data entities

Providing different serializations of entities in a file or queried using a (proxied) SPARQL endpoint.

### Further use
This server can also be extended with plugins, depending on the use case of the deployment. One can classify these plugins in *Applications*, *Trifid Extensions* and *Custom APIs*.

**Examples of Trifid Extension:**
* trifid-renderer-simple (HTML Dereferenciation UI)
* trifid-plugin-yasgui (A SPARQL UI interface)
* graph-explorer (A generic data browser)
* trifid-spex (A data model introspection tool)

**Examples of custom APIs**
* IIIF trifid plugin
* CKAN trifid plugin

## Who Uses Trifid?

Trifid is open source and meant to work out of the box for data publishers. Most users will use only the main features. We, or people that dive deeper into the code, maintain and develop instances with additional plugins.

## Trifid objectives

Trifid provides some middlewares by default.

- the most used handlers (SPARQL, fetch, …)
- the renderer (important note: renderer != template engine ; the renderer is the thing that is used to render triples, the template engine is only here to render any kind of HTML)
- some other middlewares that we may use in multiple instances (like SPEX and Graph Explorer?)

By saying "include" it's just that when you install the `trifid` package, all that middlewares are already installed (which is not the case for `trifid-core`), but you will need to manually call them in your configuration file (so that you can specify the paths/methods/hosts/config properties you want).

## Trifid-core's objectives

- configuration: parse configuration files, validate it, and take care of loading everything that is requested, like the middlewares specified in the configuration file
- include some little middlewares that may be used in many instances (like serving a directory at a specific path)
- provide some utility functions or data that can be used in any middlewares (like the config values, a logger, a basic way to render HTML content, …)

The "a basic way to render HTML content" part can be discussed if you think that this deserves a topic.
The point is that middlewares are not obliged to use them, but having something that middlewares can use to show some HTML stuff which is using the default instance header and footer is something nice to have.
Header and footer are served using nice defaults, and can be overridden for the instance.

Everything is already documented here:
- How to configure it using the config file: https://github.com/zazuko/trifid/wiki/Configuration#template-engine
- How to use it in a middleware: https://github.com/zazuko/trifid/wiki/Customize-the-templates

Currently, missing feature:
- add custom scripts and styles as documented

Everything else is already working properly.

## Middlewares objectives

Just see their README file, they should describe what they are doing.
If one middleware do not have a README file, this is an issue and someone needs to quickly provide a documentation.

## Objectives for the Trifid refactoring that we are doing

- simplify a lot how user can use it (so that it's not a tool that only us can use): new config system, better documentation, …: we are on the right direction
- upgrade all dependencies: some people (including customers) already complained about the number of vulnerabilities in the dependencies that we have ; this is the right moment to take care of fixing all deprecation warnings and upgrading everything to the latest version: nice progress on this
- convert the codebase from CommonJS to ES modules: nice progress on this
- have more people involved in the code: OK

**Comment by cristianvasquez** [comment]
Map of components

https://gitlab.zazuko.com/adm/wiki/-/wikis/Dev/libs/trifid

**Comment by MartinaElsawy** [comment]
Thomas will review and update

**Comment by l00mi** [comment]
Ready to publish https://github.com/zazuko/trifid/pull/137 once new release is imminent.

**Comment by l00mi** [comment]
@ludovicm67 this can now be merged if I understand correctly?

**Comment by ludovicm67** [comment]
Yes, I think we can do the merge!

**Comment by ludovicm67** [comment]
The merge is done.
