### ISSUE TITLE
Check why ?format=ttl is not working.

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#127]

**Comment by ludovicm67** [comment]
I provided a fix for it there: https://github.com/zazuko/trifid-renderer-entity/commit/c96ad29e001e7a2a75c97b4a80508f443b3c66d3

Examples for this resource: https://lindas.zazukoians.org/canton/23

- JSON: https://lindas.zazukoians.org/canton/23?format=json
- XML: https://lindas.zazukoians.org/canton/23?format=xml
- TTL: https://lindas.zazukoians.org/canton/23?format=ttl
