### ISSUE TITLE
Refresh on UI parts, make suggestions of missing problems.

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#128]

**Comment by cristianvasquez** [comment]
I've added the following (to be discussed)
https://github.com/zazuko/trifid-handler-sparql/issues/15

**Comment by cristianvasquez** [comment]
I've added https://github.com/zazuko/trifid/issues/130 , which is an example. It's currently in a branch (to be reviewed) . It allows running an example instance that shows different variants of the entity renderer.

**Comment by cristianvasquez** [comment]
URL: https://ld.zazuko.com/parameters
