### ISSUE TITLE
Analyse how to implement pagination and implement

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#129]
As described in #123 pagination should be implemented. It should be analysed how to implement it on the backend and fronted.

Accept:
There is a concept for pagination.

**Comment by bergos** [comment]
Maybe the [TREE](https://github.com/TREEcg/specification) ontology could be used to create triples for the client.

**Comment by cristianvasquez** [comment]
Test data here: https://ld.zazuko.com/test/people/

**Comment by cristianvasquez** [comment]
I've tested a very straightforward solution: update the container query to produce some additional (hydra) controls + hydra:Collection. 

I guess the renderer needs to handle collections as a list when they are marked as such  

Example of the data: https://ld.zazuko.com/test/people/

**Comment by l00mi** [comment]
Open questions to me:
* Do we page triples per-se, or do we look at triples with the same Subject for pagination?
* How to define starting which amount entries we do pagination?
* How is sorting handled if we do pagination?
* How can we jump to a specific page in pagination?
* Is it possible to implement "continuous scroll" (like zack-search) with the underlying pagination mechanism?

**Comment by cristianvasquez** [comment]
Hi!

Thank you for the good questions

What would help is to define some example collections, for example, 'datasets' or 'cubes,' and iterate with them. How typical is this use case? What attributes to add?

**Comment by cristianvasquez** [comment]
### Do we page triples per-se, or do we look at triples with the same Subject for pagination?

	This example is paginating the triples, only showing a triple + label

?something a ?class + a label.

Which is configured in the `containerGraphQuery` in a modified version of the trifid-handler-SPARQL middleware, which triggers each time the URL ends with a slash '/'

Like: https://ld.zazuko.com/test/people/?page=4

```sparql

    PREFIX schema: <http://schema.org/>
    PREFIX hydra: <http://www.w3.org/ns/hydra/core#>
    
    CONSTRUCT { 
      <${iri}> a hydra:Collection ;
         hydra:member ?s ;
         ${prev}
         hydra:first <${iri}> ;
         hydra:next <${iri}?page=${currentPage + 1}> .
      ?s a ?o. 
      ?s schema:name ?label.
    } WHERE { 
      ?s a ?o. 
      OPTIONAL {?s schema:name ?label. } .
      FILTER REGEX(STR(?s), "${iri}") .
      
    } limit ${pageSize} offset ${currentPage * pageSize}
    
```

I don't know if this is the best approach for the use case, but today this works out of the box.

To add more attributes for the items in the collection, one can update the underlying SPARQL in the configuration; for example, to add 'schema:Place', one needs to add an OPTIONAL in the where.

```sparql
WHERE { 
      ?s a ?o. 
      OPTIONAL {?s schema:Place ?o. } .
      OPTIONAL {?s schema:name ?label. } .
      FILTER REGEX(STR(?s), "${iri}") .
    } 
```

**Comment by cristianvasquez** [comment]
### How to define starting which amount entries we do pagination?

The example uses two parameters: `currentpage` and `pageSize`

**Comment by cristianvasquez** [comment]
### How is sorting handled if we do pagination?

I don't know; it's difficult to tell without knowing some things.

For example: 

- What attributes should a collection have while paginating?
	- Should this live in the configuration of SPARQL-Handler?
	- Should this live in the data, in a SHACL, or similar?
	- Most attributes by default?
- Should different entities, such as /people/ or /projects/ show different attributes?

**Comment by cristianvasquez** [comment]
### How can we jump to a specific page in pagination?

In the current example, it's done using the attribute 'page'

https://ld.zazuko.com/test/people/?page=3, which is the resource that denotes page 3 of the paginated collection

**Comment by cristianvasquez** [comment]
### Is it possible to implement "continuous scroll" (like zack-search) with the underlying pagination mechanism?

I think in a standalone application, this is straightforward, 

but I'm unsure of how this would work on top of the trifid templating mechanism (https://github.com/zazuko/trifid/issues/100) 

How do you think this could work @bergos, @ludovicm67

**Comment by l00mi** [comment]
@cristianvasquez Ah, now I understand your example. I think here is a high-level missunderstanding. It is not about specific resource to paginate, but much more to paginate any kind of triples in case there are e.g. 1000+ triples on a resource. This is also only an HTML UI problem. All other content negotations, need still to send all triples.

**Comment by cristianvasquez** [comment]
I see, 

 If one wants to paginate the triples in the UI then one could use parameters `currentpage` and `pageSize` for the web component.

One doesn't paginate triples but rows.


Consider this toy example:

![image](https://user-images.githubusercontent.com/361916/211313450-9e27c76f-8dd5-489f-8118-f76e52da5c69.png)

![image](https://user-images.githubusercontent.com/361916/211313497-2c30f59c-0c57-4a66-bb7c-8ff7fae00087.png)



If one is not in 'compact mode', without grouping parameters or values, this corresponds to paginating the triples.

This will be simpler to implement than the collections :)

**Comment by l00mi** [comment]
But it will still load all triples of the resourcE?

**Comment by cristianvasquez** [comment]
Yes, now it's working like this:

- Intercept the quads from previous middlewares (which can be in any format)
- transform them into something the renderer understands (the quads) 
- Group the quads by value and object to produce the rows
- Generate the HTML to send to the server.

**Comment by cristianvasquez** [comment]
To show quads as they arrive and provide a low-latency experience, we need to structure our trifid instances differently.

The middlewares need to return quads as rdf-js quads, (no turtle, no json-ld). And something like a single-page application that consumes this on top.

**Comment by ludovicm67** [comment]
The way to solve this will be to:
- create a new endpoint that is dedicated to serve requested resources (paginated) ; like a standard API endpoint, let's say at `/api/entity` for example
- in the template, render the first page server-side like we are doing now (this offers results that can be fetched without JavaScript enabled), and dynamically loads the other pages from that template in background and complete the rendered page

**Comment by l00mi** [comment]
@cristianvasquez the solution with `pageSize` as mentioned above is already implemented as of now?

**Comment by cristianvasquez** [comment]
> The way to solve this will be to:
> 
>     * create a new endpoint that is dedicated to serve requested resources (paginated) ; like a standard API endpoint, let's say at `/api/entity` for example
> 
>     * in the template, render the first page server-side like we are doing now (this offers results that can be fetched without JavaScript enabled), and dynamically loads the other pages from that template in background and complete the rendered page

As I understood recently, this is not about returning paginated resources but triples for one entity.

**Comment by MartinaElsawy** [comment]
Discussion cleared several points, level of implementation is still ongoing

**Comment by ludovicm67** [comment]
As this wrongly got closed multiple time by @bergos, a follow-up issue was created here #598.
