### ISSUE TITLE
Check performance on redirect

### ISSUE THREAD

**Issue by MartinaElsawy** [zazuko/trifid#133]
Once the redirect plugin is activated, for every dereferencing query, a additional database lookup is made.

The goal of this issue is to understand, how much additional time, for non-redirect dereferencing is needed once the plugin is active.

**Comment by MartinaElsawy** [comment]
Needed to see how redirect impacts overall performance - see also

**Comment by cristianvasquez** [comment]
I will do it like this:

- Measure without the redirect plugin
- Measure with the redirect data

	- For normal entities
	- For entities with lots of triples
	
Publish here the time difference those responses.

**Comment by l00mi** [comment]
This should now be able to be started with #155 as base.

The goal is to get a measurement, of how much overhead, the redirect functionality adds to the dereferencing.

**Comment by cristianvasquez** [comment]
I did various tests, local and remote.

## Remote

I tested a remote instance with redirects and without. The configuration has caching for SPARQL calls, therefore I observed no big difference between the two setups. However at specific runs, the server reacted slowly. This was for the two configurations. 

I'm puzzled about why, if there is already caching enabled.


## Local

These are tests with no cache and an endpoint in another network, that adds-up IO latency. As expected the middleware, in this case, is expensive, adding up proportionally to the new calls. The setup makes 1 call for redirect and two calls in trifid-handler-sparql one for exists and one for describe
 
Local (proxied)

```
autocannon -c 10 -d 30 -p 10 http://0.0.0.0:8080/adams/gomez
```


![Image](https://user-images.githubusercontent.com/361916/220327361-90a75880-8503-4e1a-b3b8-7095360c4554.png)



Local (proxied) no handle-redirect


![Image](https://user-images.githubusercontent.com/361916/220327434-b34a889b-6182-460a-8e3f-63a95f286564.png)

**Comment by cristianvasquez** [comment]
Update: I've tried to benchmark the performance of the trifid-related queries directly to Stardog without passing through Trifid. 

I'm getting so many timeouts I cannot benchmark at the moment.

**Comment by l00mi** [comment]
Okay, I just wanted to comment that the numbers make no sense as presented above.

You can try against our data.zazuko.com store ?

**Comment by cristianvasquez** [comment]
The numbers were for the local setup. 

I'm going to check the data.zazuko.com store. 

How do I present the numbers?

**Comment by l00mi** [comment]
Sorry, my remark was not well written. The presentation makes sense as you have it. But the content was not making sense.

Else to have one run with plugin-active, and one without is absolutely enough.

**Comment by cristianvasquez** [comment]
If I query stardog too often, the latency goes up, therefore when I do load-testing, I get results that do not make sense.


![Image](https://user-images.githubusercontent.com/361916/220376205-2efed09b-5004-4f59-a84f-1b3086921e8a.png)



I get things like this when I stress stardog.

Latency with queries without trifid.

![Image](https://user-images.githubusercontent.com/361916/220376961-3ee603a1-5459-4b48-9d62-eadd01a138d4.png)



Let me think over how I can measure this because, in the meantime, I don't know.
