### ISSUE TITLE
--sparql-endpoint-url CLI option stopped working

### ISSUE THREAD

**Issue by tpluscode** [zazuko/trifid#143]
In Cube Creator I configured a local trifid to run with command 

```
/app/server.js --config=/config-sparql.json --sparql-endpoint-url=http://admin:password@db.cube-creator.lndo.site/cube-creator
```

This proved simpler than creating a custom config because I only want a simple proxy with YASGUI front end.

I recently pulled a new version and now I get `unknown option '--sparql-endpoint-url'` (with or without `=`)

**Comment by ludovicm67** [comment]
Hi @tpluscode !
The new major version of Trifid is coming with a complete new configuration system.
You can have a look at: https://github.com/zazuko/trifid/wiki/Configuration or to some examples in the `instances` directory.
I enabled the `--sparql-endpoint-url` and `--dataset-base-url` parameters just now, and they should work.
Can you give it a try?

**Comment by ludovicm67** [comment]
I saw that it was still requiring the use of the `config` option ; in the next release it should work directly out of the box.
