### ISSUE TITLE
Be able to customise CSS classes in Lindas TEST for Markdown parser

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#145]

**Comment by l00mi** [comment]
Can be tweaked on the project local plugin.

Potentially that could be mentioned in the Documentation of the plugin?

**Comment by ludovicm67** [comment]
This is a custom plugin that is for Lindas only.
It is not delivered as a common plugin in a dedicated package.
@l00mi Is it something that should be the case?

**Comment by l00mi** [comment]
I feel at some point it should become a dedicated package for other use cases. But not in the context of this project phase.
