### ISSUE TITLE
Dereferencing URIs

### ISSUE THREAD

**Issue by anjomshoaa** [zazuko/trifid#149]
While dereferencing URIs, Trifid generates the following SPARQL query which throws a SPARQL parse error in the logs:

`PREFIX schema: <http://schema.org/>
CONSTRUCT {
      graph ?g {
        ?uri schema:name ?label .
      }
    } where {
      graph ?g {
        ?uri schema:name ?label
        VALUES ?uri { <http://www.w3.org/ns/sosa/hasFeatureOfInterest> }
      }
}`

The parse error is: 
`org.eclipse.rdf4j.query.parser.sparql.ast.ParseException: Encountered " "where" "where "" at line 7, column 7. `

Thank in advance for your help!

**Comment by ludovicm67** [comment]
Hi @anjomshoaa! Thanks for opening this issue.
The error should be fixed with the new Trifid version.
