### ISSUE TITLE
The entity-renderer middleware returns files instead of text/html!

### ISSUE THREAD

**Issue by anjomshoaa** [zazuko/trifid#169]
While trying to render an entity, the results are downloaded as a file with "nq" extension. The file contains the correct serialization of entity in html format.  How can I config Trifid server to serve these files with "text/html" MIME type instead?

Any help is appreciated, thanks!

**Comment by ludovicm67** [comment]
Thanks for opening the issue @anjomshoaa!

In Trifid we display by default the results in HTML format.
There is also the feature where you can get a specific format by providing a specific `Accept` HTTP header.
Are you overriding your headers?

**Comment by anjomshoaa** [comment]
Thanks for your attention @ludovicm67 

Actually this happens only when I switched to "trifid": "^4.0.1" . The same settings (proxy, sparql endpoint, port numbers, etc.) works with "trifid-core": "^1.4.0" .

Also my node.js project does nothing special and just adds a template for entity rendering: 

`
  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      path: file:./views/entity.hbs
`

**Comment by ludovicm67** [comment]
Do you get HTML content when you run the following command in a terminal (replace `/path/to/a/resource` to an existing path):

```sh
curl -vvv -H "Accept: text/html" http://0.0.0.0:8080/path/to/a/resource
```

If so, then it's just that your browser is overriding the HTTP headers (this might be the cause if you are using browser extensions like `ModHeader` or similar).
Can you try by using another browser? And/or using private browser mode?

**Comment by anjomshoaa** [comment]
Yes, I get the correctly rendered HTMl content. I digged deeper and according to log files Trifid sends 4 queries to SPARQL endpoint for dereferencing the resource (in my case <http://crispy.ai.wu.ac.at/crisp/police.8>): 

```
PREFIX http:   <http://www.w3.org/2011/http#>
    SELECT ?location ?code WHERE {
      GRAPH ?g {
            ?request a http:GetRequest ;
            http:response [
                a http:Response ;
                http:responseCode ?code ;
                http:location ?location 
            ] ;
            http:requestURI <http://crispy.ai.wu.ac.at/crisp/police.8>     
      }
    } LIMIT 1

############################

ASK { <http://crispy.ai.wu.ac.at/crisp/police.8> ?p ?o }

############################

DESCRIBE <http://crispy.ai.wu.ac.at/crisp/police.8>

############################

PREFIX schema: <http://schema.org/>

CONSTRUCT {
  ?uri schema:name ?label .
} WHERE {
  GRAPH ?g {
    ?uri schema:name ?label
    VALUES ?uri { <http://crispy.ai.wu.ac.at/crisp/police.8>  <http://www.opengis.net/ont/geosparql#hasGeometry>  <http://www.opengis.net/ont/geosparql#sfWithin>  <http://crispy.ai.wu.ac.at/crisp/cell.L1.83.421>  <http://www.w3.org/2006/vcard/ns#hasAddress>  <http://www.w3.org/2006/vcard/ns#hasEmail>  <mailto:PI-K-Villach-Landskron@polizei.gv.at>  <http://www.w3.org/2006/vcard/ns#hasTelephone>  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://crispy.ai.wu.ac.at/crisp/PoliceStation>  <http://www.opengis.net/ont/geosparql#Feature>  <http://www.w3.org/2006/vcard/ns#Organization>  <http://www.w3.org/2000/01/rdf-schema#label>  }
  }
}
```

Do you think this is normal? Also if it helps I can send the project contents which is minimal.

**Comment by ludovicm67** [comment]
So it's able to get HTML content using the `curl` command, so it's definitively an issue from the headers that your browsers is sending.

The different queries are expected:
1. check if there is a redirection defined for your resource
2. check if the resource exists
3. get all info about your entity
4. get the labels for every values that your entity is referencing

Yes, if you have something that I can check more deeply, it will be easier for me to help you to debug your application.
Do you have a repository for your app?

**Comment by anjomshoaa** [comment]
Thank you @ludovicm67 , that would be a great help. Here is my repository: 

   [https://github.com/anjomshoaa/trifid_server](https://github.com/anjomshoaa/trifid_server)

**Comment by ludovicm67** [comment]
Thanks @anjomshoaa for the repository!
I was able to see and reproduce the issue using your configuration and your SPARQL endpoint.

As I can see, the SPARQL endpoint is sending the response as a file (the `queryXXXXX.nq`), and this is what leads to trigger that download.

Can I ask you what are you using as triplestore?

We are currently testing Trifid over Fuseki and Stadog.
I tried to switch to another endpoint by keeping the rest of your configuration, and it seems that it is working as expected.

So the issue is coming from the answer from the endpoint that you are using, and this different behavior leads to the issue you described.

If I known more about what is used there, this will help me for the investigation.

**Comment by anjomshoaa** [comment]
Great, thank you so much @ludovicm67 .

Yes, it is Blazegraph and it is strange because older Trifid with the same endpoint works perfectly. For instance:  [http://crispy.ai.wu.ac.at/crisp/police.8](http://crispy.ai.wu.ac.at/crisp/police.8) . 
I take a closer look at Blazegraph and hopefully will manage to find the issue.

**Comment by ludovicm67** [comment]
Thank you @anjomshoaa for your feedback and your reactivity for this issue.

I created a follow-up issue (#170), to check the support with Blazegraph.
I will report on the new issue #170 once I will have the time to do some tests with Blazegraph, and see if we can adjust some things so that it's working directly out of the box.
