### ISSUE TITLE
Make it possible to define 302 redirects in config

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#17]
Use case is trifids where the documentation actually is on another server and we like to directly redirect. As with ld.geo.admin.ch which is right now solved by ugly html-redirect

**Comment by ktk** [comment]
You mean kind of rewrite-rules in Apache?

**Comment by l00mi** [comment]
something simple like
```
rewrite: [  
                { "", "https://blub.com"},
                {"documentation/tool1", "https://blib.com/docu"}
             ]


```

ideally the first matches **domain.tld** and **domain.tld/** and the second **domain.tld/documentation/tool1** and **domain.tld/documentation/tool1/**

**Comment by l00mi** [comment]
all good! used for geo.admin.ch
