### ISSUE TITLE
trifid autocompletion broken

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/trifid#192]
@ludovicm67 trifid/YASGUI as of now fail to autocomplete prefixes.

steps to reproduce:

1. open https://test.ld.admin.ch/sparql/#
1. type `schema:` and wait for autocomplete - but nothing happens

reason: invalid tls certificate for https://prefix.cc/popular/all.file.json - thus connection rejected by browser

**Comment by ktk** [comment]
I informed Richard, which is the author according to http://prefix.cc/about

**Comment by Rdataflow** [comment]
Hth, else we need to copy or reverse proxy or whatever is easy and maintainable

**Comment by ktk** [comment]
Our plan is to get rid of YASGUI, it is no longer maintained and the codebase is old. We think there are better ways to provide SPARQL frontends on more modern stacks like Monaco editor & LSP Protocol.

**Comment by ludovicm67** [comment]
@Rdataflow yes, thanks for reporting the issue.

I just checked again, and it seems that they finally managed to renew the certificate end of December. It should now work again as expected for now.

I'm closing this issue.
