### ISSUE TITLE
URI rewriting not working with Docker image

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [zazuko/trifid#193]
Hi;

I'm using Trifid with Blazegraph in a Google Cloud machine:

- OS image: `ubuntu-2204-jammy-v20231030`
- Blazegraph: `2.1.6-SNAPSHOT`
- Trifid (Docker): `ghcr.io/zazuko/trifid:latest`

The Blazegraph endpoint contains the following data: 

`<http://fair/data/amy-farrah-fowler> <http://schema.org/knows> <http://fair/data/mikel> .`

And it works just fine:

![Blayegraph](https://github.com/zazuko/trifid/assets/3883671/30a9738f-0f35-4271-96a3-64d26a7e5f01)

I execute Trifid with: 

`docker run -p 3031:8080 -e "SPARQL_ENDPOINT_URL=http://xxx.xxx.xx.xx:9999/blazegraph/namespace/um/sparql" -e "DATASET_BASE_URL=http://fair/" ghcr.io/zazuko/trifid`

And although I can see Trifid working:

![trifid](https://github.com/zazuko/trifid/assets/3883671/af6cb478-cd4e-45b1-becc-09f12d5f4024)

I get the following error and the Docker container simply dies:

![shell](https://github.com/zazuko/trifid/assets/3883671/579ff43b-21cb-4757-89ef-3036671b8817)

It looks like Trifid is trying to obtain a resource using dataset base URL, but it shouldn't. Perhaps the environment variables are not passed correctly to the Docker container?

Any ideas are wellcome

Thanks

Regards

PD: this is material for a Master level module on FAIR data publication

**Comment by ktk** [comment]
Thanks for the report, as I mentioned on LinkedIn we rewrite the inner workings of Trifid right now. The rewrite module used here is one of the reasons, it causes many problems and it's in its current form almost impossible to fix.

I will discuss the issue with my colleagues but my first guess is that you will have to wait for the new version to have this properly fixed.

**Comment by mikel-egana-aranguren** [comment]
Thanks. When are you expecting to release the new version?

**Comment by ktk** [comment]
That won't be ready by then I'm afraid.

What you could try is to replace blazegraph with Oxigraph (the binary version, not the WASM one we will intergrate), it's super lightweight. We never did much with blazegraph, might be that it's not behaving like we expect so it kills trifid at some point.

**Comment by mikel-egana-aranguren** [comment]
Ok thanks, I will try.

**Comment by mikel-egana-aranguren** [comment]
Hi again:

I have tried with Oxigraph (0.3.22) and Trifid (4.1.1), but it is behaving similarly: instead of querying the SPARQL endpoint, it is trying to resolve the mapped URI (`http:example.org`). 

Docker-compose:
```
version: "3"
services:
   linked_data_server:
      image: ghcr.io/zazuko/trifid:v4.1.1
      ports:
         - "8080:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://sparql_endpoint:7878/query"
         DATASET_BASE_URL: "http://example.org/"

   sparql_endpoint:
      image: ghcr.io/oxigraph/oxigraph:v0.3.22
      volumes:
         - ./oxigraph/data:/data
      ports:
         - "7878:7878"
```

Data uploaded to Oxigraph:
```
@prefix ex: <http://example.org/> . 
ex:subject ex:predicate ex:object .
```
And when I access `localhost:8080`, not even  trying to retrieve `ex:subject`, the trifid container dies with the following message:

```
linked_data_server_1  | WARNING: 'SPARQL_PROXY_CACHE_URL' environment variable is not set
linked_data_server_1  | [14:25:15.920] INFO (trifid-core/6): Trifid instance listening on: http://0.0.0.0:8080/
linked_data_server_1  | 172.26.0.1 - - [31/Jan/2024:14:25:27 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
linked_data_server_1  | /app/node_modules/sparql-http-client/lib/checkResponse.js:7
linked_data_server_1  |   const err = new Error(`${res.statusText} (${res.status}): ${message}`)
linked_data_server_1  |               ^
linked_data_server_1  | 
linked_data_server_1  | Error: Not Found (404): <!doctype html>
linked_data_server_1  | <html>
linked_data_server_1  | <head>
linked_data_server_1  |     <title>Example Domain</title>
linked_data_server_1  | 
linked_data_server_1  |     <meta charset="utf-8" />
linked_data_server_1  |     <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
linked_data_server_1  |     <meta name="viewport" content="width=device-width, initial-scale=1" />
linked_data_server_1  |     <style type="text/css">
linked_data_server_1  |     body {
linked_data_server_1  |         background-color: #f0f0f2;
linked_data_server_1  |         margin: 0;
linked_data_server_1  |         padding: 0;
linked_data_server_1  |         font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
linked_data_server_1  |         
linked_data_server_1  |     }
linked_data_server_1  |     div {
linked_data_server_1  |         width: 600px;
linked_data_server_1  |         margin: 5em auto;
linked_data_server_1  |         padding: 2em;
linked_data_server_1  |         background-color: #fdfdff;
linked_data_server_1  |         border-radius: 0.5em;
linked_data_server_1  |         box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
linked_data_server_1  |     }
linked_data_server_1  |     a:link, a:visited {
linked_data_server_1  |         color: #38488f;
linked_data_server_1  |         text-decoration: none;
linked_data_server_1  |     }
linked_data_server_1  |     @media (max-width: 700px) {
linked_data_server_1  |         div {
linked_data_server_1  |             margin: 0 auto;
linked_data_server_1  |             width: auto;
linked_data_server_1  |         }
linked_data_server_1  |     }
linked_data_server_1  |     </style>    
linked_data_server_1  | </head>
linked_data_server_1  | 
linked_data_server_1  | <body>
linked_data_server_1  | <div>
linked_data_server_1  |     <h1>Example Domain</h1>
linked_data_server_1  |     <p>This domain is for use in illustrative examples in documents. You may use this
linked_data_server_1  |     domain in literature without prior coordination or asking for permission.</p>
linked_data_server_1  |     <p><a href="https://www.iana.org/domains/example">More information...</a></p>
linked_data_server_1  | </div>
linked_data_server_1  | </body>
linked_data_server_1  | </html>
linked_data_server_1  | 
linked_data_server_1  |     at checkResponse (/app/node_modules/sparql-http-client/lib/checkResponse.js:7:15)
linked_data_server_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
linked_data_server_1  |     at async ParsingQuery.select (/app/node_modules/sparql-http-client/StreamQuery.js:73:5)
linked_data_server_1  |     at async ParsingQuery.select (/app/node_modules/sparql-http-client/ParsingQuery.js:41:20)
linked_data_server_1  |     at async HttpInRDFHandler.queryRedirect (file:///app/node_modules/@zazuko/trifid-handle-redirects/index.js:95:22)
linked_data_server_1  |     at async HttpInRDFHandler.get (file:///app/node_modules/@zazuko/trifid-handle-redirects/index.js:117:22) {
linked_data_server_1  |   status: 404
linked_data_server_1  | }
linked_data_server_1  | 
linked_data_server_1  | Node.js v20.10.0
basquecountryinstitutionstransparentrelationsgraph_linked_data_server_1 exited with code 1
```

Thank you

Regards

**Comment by ktk** [comment]
We are close to a first release now, let's test that as soon as it is out.

**Comment by mikel-egana-aranguren** [comment]
Sure, please do let me know in this thread or in LinkedIn

Thanks

**Comment by ktk** [comment]
@mikel-egana-aranguren you might want to try V5! https://github.com/zazuko/trifid/releases/tag/trifid%405.0.0

**Comment by mikel-egana-aranguren** [comment]
Sure, I will give it a try and let you know how it goes

**Comment by mikel-egana-aranguren** [comment]
Hi @ludovicm67

It works perfectly. Thanks for the detailed response, nice!

Regards

**Comment by ludovicm67** [comment]
Hi @mikel-egana-aranguren 

Thank you for your feedback, and I'm glad to see that everything is working as expected for you now :)
I will close this issue.

Best,
Ludovic.
