### ISSUE TITLE
Linked Data Platform

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [zazuko/trifid#2]
To what extend does Trifid conform to the Linked Data Platform recommendation (https://www.w3.org/TR/ldp/)?

Thanks

**Comment by ktk** [comment]
@mikel-egana-aranguren not at all, this is purely doing dereferencing so far. @bergos might be able to give some comments about how/where LDP support could be added. Note that we don't have a use case so far so I don't think we will add our self that anytime soon.

**Comment by mikel-egana-aranguren** [comment]
@ktk one of the requirements in a [Linked Open Data](http://www.contratacion.euskadi.eus/w32-1084/es/contenidos/anuncio_contratacion/expx74j21656/es_doc/es_arch_expx74j21656.html) project is to develop an LDP compliant Linked Data server. I am not very sure LDP has any traction whatsoever, nor if it is worthy the hassle, so I'm pinging around to see if there are any products/experiences on implementing LDP. I think I will simply try to pass on the LDP requirement, since no one seems to "take LDP seriously".

thanks

regards

**Comment by ktk** [comment]
@mikel-egana-aranguren I have a bit a difficult relationship with LDP. While I get the idea we probably would have done it completely hypermedia driven, like with Hydra. This is something we might do sooner or later, funds that allow us to work on something push the priority :)

On the other hand I do see that some projects start to use LDP quite heavily, one of them is [Fedora](https://wiki.duraspace.org/display/FEDORA47/Linked+Data+Platform). Fedora is a pretty serious and heavily used project so I am curious if/how it will get traction there.

**Comment by ktk** [comment]
I close this for the moment, don't think we will implement LDP anytime soon.
