### ISSUE TITLE
Collect "HTML referer" and provide backlinks.

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#24]
The idea is to collect links on a resource (from random HTML documents). The idea is to write a middleware which collects such *HTML referer* links. Every new referer creates a *task* inside a triplestore which can in a separate process consumed and add the necessary triples to the resources.

Only the caching front-end is problematic here as it potentially hides hits on the resource from trifid. The following options are possible:
- Passthrough the hits: Can we tell the caching front-end to deliver the cached version but anyway hit the trifid instance? (@ktk any idea?)
- Separate Proxy: Put a separate process in front of varnish which only collects the referers.
- Analyze Log: Analyse the log of varnish.

In general if possible the first option will keep the overall architecture lean. The second option is most flexible and the third option creates a dependency to the used caching front-end.

**Comment by vhf** [comment]
I don't understand the idea or the goal, perhaps an example would help?

**Comment by l00mi** [comment]
First of all please consider this just as an idea. It has no priority, and no customer asks for this feature.

**Comment by l00mi** [comment]
The main goal of this feature is to measure how and from where people link to a Trifid Instance. (To e.g. evaluate the impact of a dataset, resource.)

A secondary goal is to see if there are potential links to another dataset which can be set. (If e.g. a query hops from one domain to another.)

So a first step would be to analyse the incoming headers for https://en.wikipedia.org/wiki/HTTP_referer, and if present to collect it insert it as triples in the store.

**Comment by l00mi** [comment]
And an example.
From a website, or RDF Resource we have a link to https://ld.geo.admin.ch/boundaries/municipality/21
The header does contain HTTP_referer. This gets saved to the triple store to analyse in a later step.

**Comment by bergos** [comment]
In our SPARQL store we usually have only data for our domains. Let's use `ld.geo.admin.ch` as example, as it's referenced many times. From `ld.geo.admin.ch` perspective, most triples look very similar to:

```turtle
@prefix s: <http://schema.org/> .

<https://ld.geo.admin.ch/boundaries/municipality/2701>
  a s:AdministrativeArea ;
  s:name "Basel" .
```

All Named Node subjects are in the owners namespace. Now it would be nice to also see reverse triples with the object using the namespace of the owner. For example the data of Basel points to it:

```turtle
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<https://ld.data-bs.ch/code/raum/Gemeinde2701>
  rdfs:label "Basel" ;
  owl:sameAs <https://ld.geo.admin.ch/boundaries/municipality/2701> .
```

The distributed nature of the Web does not give easy access to data not from your namespace. First you need to find it somehow. This issue actually covers only the first part, the discovery of resources pointing to our data. Crawling the Web would be one option to find resources on other domains referencing to our data. An alternative is the information we get from people following links, coming from other domains. For the example above, if somebody comes from the Basel page to `ld.geo.admin.ch`, the HTTP request looks like this:

```
GET /boundaries/municipality/2701 HTTP/1.1
Host: ld.geo.admin.ch
...
Referer: https://ld.data-bs.ch/code/raum/Gemeinde2701
```

We could store the information of the `Referer` as a triples in our store. The data could look like this, with information about the time of the request.

```turtle
@prefix r: <http://example.org/request/> .

<https://ld.geo.admin.ch/boundaries/municipality/2701>
  r:hasRequest [
    r:date "2019-05-08T00:00:00.000Z"^^xsd:dateTime ;
    r:referFrom <https://ld.data-bs.ch/code/raum/Gemeinde2701>
  ] .
```

Maybe the [HTTP Vocabulary](https://www.w3.org/TR/HTTP-in-RDF10/) could be useful if more information should be stored. Also the second step, retrieving the data, should be kept in mind. So maybe a data structure more aligned for the two step process could be useful.

**Comment by l00mi** [comment]
Can this be solved with a generic middleware collecting activity?
