### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#31]
There should be tests for all features of Trifid.

* Express Middleware tests.
* Coverage tests.
* E2E Tests? (Frontend)

https://kentcdodds.com/blog/static-vs-unit-vs-integration-vs-e2e-tests

**Comment by cristianvasquez** [comment]
@ludovicm67 or @bergos 
Is [this](https://github.com/zazuko/trifid/wiki/Packages) the list of packages to add tests?

**Comment by cristianvasquez** [comment]
Hi, another search doesn't help me; it distracts me. 

I would rather mark the ones that are priority, don't you agree?

**Comment by l00mi** [comment]
Main packages have tests, and there is a pending issue to verify the tests on all plugins. I am closing this for now. But keep in mind testing can alway be improved!
