### ISSUE TITLE
Link to a live demo (or production site) in README

### ISSUE THREAD

**Issue by danmichaelo** [zazuko/trifid#32]
Would be nice to check it out without downloading and getting it up and running locally :)

**Comment by ktk** [comment]
@danmichaelo good point, will add that. Some samples:

* Default view: http://lod.opentransportdata.swiss/didok/8500011
* Customized for one gov entity in Switzerland: https://ld.geo.admin.ch/boundaries/municipality/296

**Comment by akuckartz** [comment]
:+1:
