### ISSUE TITLE
Report about npm, node and Trifid version

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#33]
eventually /.well-known/version ?

**Comment by l00mi** [comment]
or as header

**Comment by bergos** [comment]
Output of `npm version` and the `package.json` in `cwd: || trifid:` should be attached to the locals variables via a plugin. A static view can be used to generate a HTML report. Maybe also the path to a REST API can be  specified.

**Comment by vhf** [comment]
What's the goal here, who should be able to access these information and how?

**Comment by l00mi** [comment]
The goal is to have a specific place to check the current running version of Trifid.
(Mostly for debugging purposes where we do not have access to the deployment enviroment itself. e.g. Swisstopo.)
The information regarding the version shall be public. Therefore it should not expose any security sensible information. The version of the npm packages are not considered as sensible.
We did not yet define how the information shall be exposed. Multiple options:
* As part of the template (e.g. in the footer). 
  (+)easy to spot
  (-) can be overwritten by customer
* At a specific location like /.well-known/version.
 (+) alway available
 (-) hidden (only people which now the feature find it)

**Comment by vhf** [comment]
I suggest an HTML page available at `/about`, or `/about-trifid` if we want to avoid name clashes at all costs.

**Comment by l00mi** [comment]
We use the .well-known/ path already for https://www.w3.org/TR/void/. That is the only reason why I propose this path as it is an [IANA standard](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) for such "meta" data locations. But there is nothing which speaks against your propositions.
So I happily leave the decision up to you.

**Comment by vhf** [comment]
> We use the .well-known/ path already for https://www.w3.org/TR/void/. 

Interesting, I didn't know we were already using this. Could you show me where it's implemented?

**Comment by bergos** [comment]
Maybe under `/trifid/about`, for the case that we need more resources around Trifid. I would not use `.well-known/` as the resources under this path are expected to be public. Depending on whom you ask in the security community some may tell you that the version information should not be public.

It would be nice to have the information also as RDF. If the Express middleware route is in the right place, it will also go through the HTML renderer, for a more readable version. I checked the [DOAP](https://github.com/ewilderj/doap) ontology if it's possible to describe an installation, but it looks like it can only describe a software project. On schema.org I found [EntryPoint](https://schema.org/EntryPoint), which should fit for our use case. Trifid, node and npm can be described with [SoftwareApplication](https://schema.org/SoftwareApplication).

Example:

```turtle
@prefix s: <http://schema.org> .

<http://example.org/> a s:EntryPoint;
  s:actionApplication [ a s:SoftwareApplication;
    s:name "Trifid";
    s:softwareVersion "1.2.3";
    s:softwareRequirements [ a s:SoftwareApplication;
      s:name "node";
      s:softwareVersion "4.5.6";
    ], [ a s:SoftwareApplication;
      s:name "npm";
      s:softwareVersion "7.8.9";
    ]
  ].
```

The subject of EntryPoint only matches protocol + host with the request which would be in this case `http://example.org/trifid/about`.

https://www.w3.org/TR/void/ is not implemented, it's just in our data. There are triples in the SPARQL store for that resource. So the work is done by the SPARQL handler.

**Comment by ktk** [comment]
> > We use the .well-known/ path already for https://www.w3.org/TR/void/.
> 
> Interesting, I didn't know we were already using this. Could you show me where it's implemented?

Swisstopo is doing it for example, see https://ld.geo.admin.ch/.well-known/void. This is done by simply adding triples to the triplestore with this subject URI so there is no special config or anything needed.

**Comment by ktk** [comment]
If we still do we should think about how we expose that first. From a security POV exposing this information to the public is not a good idea. This means it should be possible to restrict this at least to IP ranges and maybe also users. And this implies there is some kind of authentication in there which we might not want to add to Trifid in a first place.

Maybe this should only be exposed to logging.

**Comment by l00mi** [comment]
It can be simple, but exposing which TRIFID version is running I would argue has positive security implications. As in we can check easily what is running and upgrade if necessary.

**Comment by ktk** [comment]
The one that has to do the update knows the banner, for everyone else it's an exposure. See for example [OWASP](https://wiki.owasp.org/index.php/Testing_for_Web_Application_Fingerprint_(OWASP-IG-004)). Shodan & co live from this
