### ISSUE TITLE
make default query configurable

### ISSUE THREAD

**Issue by juliustens-db** [zazuko/trifid#334]
Hey there! First of all, thanks for the great project! This is just the missing puzzle piece in the linked data ecosystem I was desperately longing for a few years ago ❤️ 

Now to my "issue": I think it would be useful to be able to configure a custom default query shown to people who open the YASGUI editor for the first time (e.g. to customize the default prefixes, showcase a simple query on your data, or both).

Given my understanding of YASGUI, there is a parameter for that, which would only need to be exposed and passed via the plugin config. I'd gladly create a PR for this change, but wanted to get some feedback first if anyone objects to that 😄.

**Comment by ktk** [comment]
Hi Julius,

Thanks for the kind words!

Indeed not a bad idea, the ?s ?p ?o is a bit very generic and not very useful for newcomers indeed.

I think it's not a bad idea to make the default query easier configurable so users can adjust it to whatever they think makes more sense. I would just propose that it does not change the default config in case it's not touched.

Also I think it's related to https://github.com/zazuko/trifid/issues/59, the question is always what should a good starting page be and maybe we should think about that in this issue as well.

**Comment by ludovicm67** [comment]
Done! It's now possible to configure the default query using the `defaultQuery` configuration field of the Trifid plugin.

Here is an example: https://github.com/zazuko/trifid/blob/7ef2e4443ac71c86c935e2f9c5716206b074c54f/packages/yasgui/README.md

Released in `trifid-plugin-yasgui` v3.1.0 which is part of `trifid` v5.0.3.

**Comment by juliustens-db** [comment]
Thanks!!! ❤️
