### ISSUE TITLE
Node8 problems with content-negotiation if Varnish in front.

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#35]
Since node8 the content-negotiation is not taken into account by varnish. This follows with the effect that what ever kind of accept header was set first gets cached, all queries, regardless of the Accept header are delivered from cache with the answer of the first accept header send.

**Comment by ktk** [comment]
Sound like `Vary` header is not set anymore. Can you check if this one gets through?

**Comment by vhf** [comment]
Could you point me to the varnish config?

**Comment by ktk** [comment]
AFAIK this is solved long time ago, closing
