### ISSUE TITLE
Link headers are not rewritten with Node v8

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#36]
Link headers sent by the hydra-box middleware are not rewritten if `datasetBaseUrl` is set and Node version 8.x is used. It works with Node version 6.x.

**Comment by vhf** [comment]
@bergos Is this still an issue? If so, could you show an example?

**Comment by bergos** [comment]
I think it was fixed with [this commit](https://github.com/zazukoians/camouflage-rewrite/commit/17b17c2267a8c842977237268fe2e6b561b2556e), which is included in the latest version of `camouflage-rewrite`. Let's close this issue. If it's still a problem, we can reopen the issue.
