### ISSUE TITLE
Read/Write Queries

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#37]
For writing of public users to a Triplestore we need facilities to validate the INSERT and UPDATE queries for corect (avoid malicious) behavoiur.

What are the possibilities here?
* Sparql Proxy checking the Sparql query.
* Specific API per usecase. (Hydra)
* Graph Protocol with SHEX/shacle validation.
* Temporary graph with validation. (Write to copy of graph without check. Test graph after write of corectness, commit to final graph if correct.)
* ...?

**Comment by bergos** [comment]
- Any SPARQL approach might get to complex. It would require to parse and understand the query, which gets quite complex very fast. It would require a language/ontology for SPARQL validation, which doesn't exist yet. If we allow only a subset, we are already close to Hydra Box templates.
- Hydra Box has all the incoming data (POST, PUT, but also GET via IRI Templates) as `req.graph`. It would be easy to add a middleware before the actual SPARQL code, which does the validation. Maybe a generic SHEX/SHACL validation middleware could be implemented. A Hydra operation is required for each use case.
- Graph Store HTTP Protocol could be implemented as middleware, which generates a `req.graph` property on the request. Than the logic would be the same like in the Hydra Box approach.
- Temporary graph would just solve the problem of validation, but would still require a interface like SPARQL, Graph Store or Hydra to receive the graph data

For the Hydra Box approach, most of the code is already written. New Hydra operations for each use case is not really a drawback, cause the other approaches would require to extend the validation. Also the Hydra operation structures already the different use cases.
