### ISSUE TITLE
mime-type `n-triples` isn't compressed

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/trifid#472]
**repro steps**
```sh
curl -v 'https://test.ld.admin.ch/query' -X POST -H 'Accept: application/n-quads' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'query=CONSTRUCT%20%7B%20%3Fsub%20%3Fpred%20%3Fobj%20.%20%7D%20%0AWHERE%20%7B%0A%20%20%3Fsub%20%3Fpred%20%3Fobj%20.%0A%7D%20LIMIT%201000' > /dev/null
```

**expected**
response header with `content-encoding: gzip`

**Comment by ludovicm67** [comment]
@Rdataflow Thank you for the bug report and the PR. I will take a look 👍

**Comment by Rdataflow** [comment]
I just went through all of the YASGUI dropdown format options for a SELECT and a CONSTRUCT to check if something doesn't compress. Feel free to add or alter whatever seems best to you :+1:

**Comment by ludovicm67** [comment]
From all the test I did, the `application/sparql-results+json; charset=utf-8` was not able to work anymore with your changes. I added a commit to add support for parameterized content-types to solve the issue 😄
