### ISSUE TITLE
URI with hashtag in it is not correctly dereferenced

### ISSUE THREAD

**Issue by akolk** [zazuko/trifid#574]
The https://modellen.kkg.test.kadaster.nl/def/imxgeo-ext#gebouwType gets truncated to https://modellen.test.kkg.kadaster.nl/def/imxgeo-ext. This looks to be caused by Fastify stripping the #gebouwType. Is by desgin or is this an oversight?

**Comment by tpluscode** [comment]
This is by the web's design. Hash fragment is only local and not transferred to the server.

See for example https://stackoverflow.com/questions/3664257/why-is-the-hash-part-of-the-url-not-available-on-the-server-side
