### ISSUE TITLE
Integrate a Class (and/or Predicates) Search based on zack-search

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#61]
E.g. under /classes we can search for all classes inside the endpoint. Through links we can open SPARQL queries limiting to this class.

**Comment by ktk** [comment]
I like the idea but not sure how this would work, some questions:

- how would I search for the classes, would I use text search in zack and it would search for names of classes?
- As a result I would get back instances of these classes?
- Could I do more filtering than just that?

**Comment by l00mi** [comment]
I propose to have two "types" in the result list for a start, classes and properties (in RDFS speak). I think we should only show the description of this classes. (Not the instances of it, that might not scale well UX wise.)

It shall be a "meta" search for developers.

I would filter on names and descriptions of these, and let filter by "classes" or "property" only.

Potentially later we can also add other meta descriptions (OWL, SHACL) and also introspecting (non defined classes and properties.)

**Comment by l00mi** [comment]
Closing for now, as we have a introspection with graph-explorer.
