### ISSUE TITLE
Epic: Switch Basic Design to new Zazuko Design

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#63]
Design similar to: https://github.com/zazuko/zazuko.com

**Comment by l00mi** [comment]
Finalize the design.

**Comment by MartinaElsawy** [comment]
Check priority with Michael for Go Live

**Comment by MartinaElsawy** [comment]
Input Adrian: better to have solid basic design for now and improve after for 3.1 instead of switching now to "broken orange" and half solved new design

**Comment by ludovicm67** [comment]
The new Zazuko design is in place, but will be improved with the future releases.
