### ISSUE TITLE
Yasr: Openlayers plugin

### ISSUE THREAD

**Issue by ktk** [zazuko/trifid#70]
The [Geo](https://triply.cc/docs/yasgui#geo) plugin is now closed-source. We need an open alternative for 2D stuff as this is essential.

We need an at least feature-par replacement based on [openlayers-elements](https://github.com/zazuko/openlayers-elements)

**Comment by ludovicm67** [comment]
This was done here: https://github.com/zazuko/trifid-plugin-yasgui/blob/main/plugins/map.js
