### ISSUE TITLE
Replace UI of default renderer

### ISSUE THREAD

**Issue by ktk** [zazuko/trifid#72]
Replace outdated renderer with a one that uses an up-to-date, extendable RDF UI framework

**Comment by ktk** [comment]
The renderer needs to be able to handle paging/lazy-loading

**Comment by bergos** [comment]
Example for a resource with many triples and long loading time: https://ld.bs.ch/cube/100128/observation/

**Comment by l00mi** [comment]
@cristianvasquez link to the Zazuko Style repo.

**Comment by l00mi** [comment]
@cristianvasquez do we have paging / lazy loading yet?

**Comment by bergos** [comment]
We have two issues for the pagination topic:

https://github.com/zazuko/trifid/issues/129
https://github.com/zazuko/trifid/issues/123

@l00mi as we track the pagination in separate issue, can we close this issue?

**Comment by l00mi** [comment]
Yes, thank you.
