### ISSUE TITLE
Yasgui: Quickfix URL shortener

### ISSUE THREAD

**Issue by ktk** [zazuko/trifid#73]
Needs to be a drop-in replacement hosted by Zazuko for replacing the Yasgui URL shortener which is no longer supported.

**Comment by ktk** [comment]
Not to be confused with #71 which will be more advanced & only with new Yasgui.

**Comment by vhf** [comment]
Plan is to use https://github.com/thedevs-network/kutt for this.

**Comment by vhf** [comment]
Here it is: `https://s.zazuko.com/api/v1/shorten?url=…`
