### ISSUE TITLE
Easy start

### ISSUE THREAD

**Issue by Matyuna** [zazuko/trifid#82]
Hello! I really liked your tool in terms of ontology dereferencing, but I don't know how to work with JSON. Tell me, is it possible to quickly configure the server in such a way as to be able to de-referencing an entire ontology (for example, a file in owl or ttl format), as is already available in the example with the big bang theory?

**Comment by ktk** [comment]
@Matyuna yes that is possible, we do that as well ourself. Basically you would simply adjust the big-bang example and load your ontology instead.
