### ISSUE TITLE
Setting DATASET_BASE_URL blocks requests

### ISSUE THREAD

**Issue by mielvds** [zazuko/trifid#91]
I'm setting up Trifid with Blazegraph via `docker-compose` like so:

```
version: "3"

networks:
  sparql:
    driver: bridge
services:
  blazegraph:
    image: blazegraph:2.1.5
    ports:
      - "8090:8080"
    volumes:
      - "$PWD/config/RWStore.properties:/RWStore.properties"
      - "$PWD/data/:/data"
    networks:
      - sparql
  trifid:
    image: zazuko/trifid
    ports:
      - "8092:8080"
    depends_on:
      - blazegraph
    #command:
    volumes:
      - "$PWD/config/config-trifid.json:/app/config-trifid.json"
    environment:
  #    - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DEBUG=trifid:*
      - TRIFID_CONFIG=/config-trifid.json
      - SPARQL_ENDPOINT_URL=http://blazegraph:8080/bigdata/namespace/organizations/sparql
      - DATASET_BASE_URL=http://data.meemoo.be/
    networks:
      - sparql
   ```

my `config-trifid.json`:

```json
{
  "baseConfig": "trifid:config-sparql.json",
  "sparqlEndpointUrl": "env:SPARQL_ENDPOINT_URL",
  "datasetBaseUrl": "env:DATASET_BASE_URL"
}
```

When ` - DATASET_BASE_URL=http://data.meemoo.be/` is commented out, everything works fine. I can reach yasgui and perform queries. But when this line is active, all requests 'hang', suggesting the event loop is blocked somewhere when setting a base url. Any idea on what I'm missing?

**Comment by thewilkybarkid** [comment]
Run into the same problem using `"datasetBaseUrl": "http://localhost:8080/"` to allow connections between Docker containers.

Using cURL I can see the successful `200 OK` response complete with the expected body, but seems like the response itself is never finished so it hangs.

**Comment by ktk** [comment]
I don't really have an idea but @bergos might have a look at it later. We plan to refactor Trifid and update quite some parts in it within the next weeks.

**Comment by bergos** [comment]
@ktk @sandhose can we switch to node v12 based images in [Dockerfile](https://github.com/zazuko/trifid/blob/master/Dockerfile#L1)? There are known issues with higher node versions at the moment (see #83)

**Comment by ktk** [comment]
Ok for me

**Comment by thewilkybarkid** [comment]
In case it helps I'm successfully using `hijackresponse` to rewrite the JSON-LD context in Node 14 (https://github.com/sciety/api-prototype/blob/1c1498a7532df1904452f1b965d18973ba25441a/trifid/src/json-ld-context.js).

**Comment by mielvds** [comment]
> Thanks for the response all! Would the switch to node 12 resolve my issue?

it does btw

**Comment by l00mi** [comment]
@ludovicm67 can you please check if the docker version is version 12?

**Comment by ludovicm67** [comment]
The Docker image was using `node:lts-alpine` as base image, which is currently providing Node v14.16.0.
I updated it so that it uses `node:12-alpine` as base.
The issue should be fixed now.

**Comment by l00mi** [comment]
@mielvds thanks for reporting! @ludovicm67 and @bergos thanks for solving.

**Comment by l00mi** [comment]
@mielvds I am curious, where do you use Trifid? Is it public?

**Comment by mielvds** [comment]
I work for the Flemish Institute for Archives now; we store a lot of audiovisual material from the cultural sector. I use trifid to expose the information that is stored in our KG, which is very much under-construction, in a simple en pretty way. The main reason is to demonstrate to my organisation what our metadata as KG would enable. Therefore, I am very interested in gettting the graphexplorer and SPEX plugins running as well. Currently, nothing is public for the simple reason that we are still exploring and don't have the rights to expose the metadata from our partners without consent.

**Comment by l00mi** [comment]
Exciting, please ping once you can show something!

**Comment by l00mi** [comment]
Exciting, please ping once you can show something!
