### ISSUE TITLE
Problem with special characters in the path

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#93]
In some set-ups we see problems with special characters in the path.

E.g. from https://environment.ld.admin.ch/foen/ubd0037/3/observation/ pointing to https://environment.ld.admin.ch/foen/ubd0037/3/observation/2015/AKern/StraL/Fla/%3EIGWESII/N

while being accessible through SPARQL https://s.zazuko.com/x7MHZ

**Comment by bergos** [comment]
fixed in https://github.com/zazuko/trifid-handler-sparql/pull/12
