### ISSUE TITLE
Check if plain express middleware interfaces can be used for plugins

### ISSUE THREAD

**Issue by bergos** [zazuko/trifid#98]
The main reason the plugin interface was established is the easy access to the express application object.  Access to the application object is required for use cases like registering the view handler, as done in the [cotton candy plugin](https://github.com/zazuko/trifid-plugin-cotton-candy/blob/master/index.js#L8-L16). It should be checked if it can be done inside a middleware with the [application attached to the request](http://expressjs.com/en/4x/api.html#req.app). If all use cases can be covered, the plugin interface should be abandoned.

**Comment by l00mi** [comment]
@bergos has this new perspective any influence on the current plug-ins? Does it make sense to change any of them? If so please open an new ticket, and in any case lets close this one.

**Comment by ludovicm67** [comment]
Yes, this will require to adapt all Trifid plugins to use the new middleware factory.
Many packages are already using the new configuration system.
For the missing ones, I will prioritize the one we need for Lindas, this is something that is part of my work for setting up an instance that points to Lindas, and the work will be tracked here: https://github.com/zazuko/issues-private/issues/136.
